### ISSUE TITLE
Issues in Facebook post

### ISSUE THREAD

**Issue by burrowss** [vanslykej/vanslykej.github.io#2]
In reference to 034326d2af0973648c6aff596effb7dfdacd35e2

First paragraph, change doesn't to does not. Delete so before so prominent. 

Second paragraph, delete basically in the first sentence. 

Third paragraph, capitalize Messenger since it's a Facebook product. Allows should be allow.

Add TL;DR. Overall it's a very good article with solid points and is well written. Nice job so far.

**Comment by vanslykej** [comment]
Thank you for the suggestions, I have made the changes that you recommended. I think the work looks good, but let me know if there are any final suggestions.
