### ISSUE TITLE
Issue on 82576f9

### ISSUE THREAD

**Issue by cookc3174** [vanslykej/vanslykej.github.io#3]
So what you have wrote makes sense. The only error that I found was this line in paragraph one; "However, as this is obviously not plausible, a very common struggle for people today is being smart with and conserving their money." This sentence is a pretty lengthy. I feel that it should be broke up into two sentences. Maybe you could try this: "However, as this obviously not plausible. A very common struggle for people today is being smart and conserving their money."

**Comment by vanslykej** [comment]
Thank you for the suggestion and I have implemented the changes.

**Comment by vanslykej** [comment]
I have finished my full draft let me know what you think

**Comment by cookc3174** [comment]
yeah I do it tomorrow and I'll have mine finished by the end of Tuesday.

**Comment by cookc3174** [comment]
I read your entire draft and I really do not think anything needs to be added. Everything seems to flow very smooth and I really didn't see any errors. Overall, it was well written and definitely catches the reader's interest.

**Comment by vanslykej** [comment]
Thanks Chris. Thanks for your input throughout writing this article.
