### ISSUE TITLE
Edits/suggestions

### ISSUE THREAD

**Issue by burrowss** [vanslykej/vanslykej.github.io#5]
In reference to: e0bb4f429da4ea5be93296c28f7e4baa3f9e457b

In the first paragraph, I'd suggest eliminating  "and its effect on our lives" in the first sentence since it seems a bit redundant. In the same sentence, I think getting rid of "also" and "getting better at". Other than that though, it is a very strong piece. Great work!

**Comment by vanslykej** [comment]
Thank you for the suggestions I made the changes.
