### ISSUE TITLE
Plagiarism Rough Draft Feedback

### ISSUE THREAD

**Issue by burrowss** [vanslykej/vanslykej.github.io#6]
In reference to 6194ce2b38bf8bbeaa4999cb7d366600a37c2630

I don't think usurp is the right word for the second paragraph. Maybe use "eclipse" or something like that. In the following sentence, I'm not sure if "tasking" is right but I'm not quiet sure what you should replace it with.

When discussing turnitin, you say that schools aren't using it enough. It seems to contradict your claim that the Internet is making plagiarism easier. It is a good concession but you are just fuelling the oppositions argument. Include something like, "although this makes it harder to plagiarize, and should be utilized, it is not enough".

In the last paragraph, the second sentence is a bit long and worded weirdly. Reword it or break it up.

Throughout your article, I feel as though you are saying "I think" too much. It may detract from your arguments due to the passive voice. Even just getting rid of "I think" would help since it takes more of a stance.

If you can, try to find some statistics and sources that could help bolster your arguments. Overall it is good.

**Comment by burrowss** [comment]
Also read through your article out loud to catch any grammatical mistakes as I believe there may be some with run on sentences and commas, etc.

**Comment by vanslykej** [comment]
Thanks for the suggestions, I will take a look at some changes.
